version: '3.9'

services:
  nginx:
    container_name: FOSNginxServer
    image: nginx:stable-alpine
#    platform: linux/amd64
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www
      - ./docker/server/server.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
  php:
    build:
      context: docker/php/php81
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www
    networks:
      - backend
  mysql:
    image: mysql:8.0.33
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_DATABASE: octoDb
      MYSQL_USER: octoRoot
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
        - MysqlVolume:/var/lib/mysql
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
#    platform: linux/amd64
    links:
      - php
    ports:
      - '8081:80'
    environment:
      - PMA_ARBITRARY=1
    networks:
      - backend

volumes:
  MysqlVolume:

networks:
  backend: