version: '3.9'

services:
  nginx:
    container_name: FOSNginxServer
    image: nginx:stable-alpine
#    platform: linux/amd64
    ports:
      - '8080:80'
    volumes:
      - ./../app:/var/www
      - ./../docker/server/server.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
  php:
    build:
      context: php/php81
    ports:
      - '9000:9000'
    volumes:
      - ./../app:/var/www
      - ./../docker/php/php81/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
  mysql:
    image: mysql:8.0.33
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
        - MysqlVolume:/var/lib/mysql
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
#    platform: linux/amd64
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=${UPLOAD_LIMIT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /sessions
    depends_on:
      - php
      - mysql
    networks:
      - backend

volumes:
  MysqlVolume:

networks:
  backend: