version: '3.9'

services:
  nginx:
    container_name: FOSNginxServer
    image: nginx:stable-alpine
#    platform: linux/amd64
    ports:
      - '8080:80'
#      - '8081:80'
    volumes:
      - ./../apps/main-site:/var/www/main-site
      - ./../docker/server/projects/main-site/server.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
#  php:
#    build:
#      context: php/php81
#    ports:
#      - '9000:9000'
##      - '9009:9000'
#    volumes:
#      - ./../apps/main-site:/var/www/main-site
#      - ./../docker/php/php81/php.ini:/usr/local/etc/php/php.ini
#    networks:
#      - backend
  php:
    build:
      context: php/php84
    ports:
      - '9001:9000'
#      - '9010:9000'
    volumes:
      - ./../apps/main-site:/var/www/main-site
      - ./../docker/php/php84/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
  mysql:
    image: mysql:8.0.33
    ports:
      - '3306:3306'
#      - '3310:3310'
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_TCP_PORT: 3310
    volumes:
        - MysqlVolume:/var/lib/mysql
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
#    platform: linux/amd64
    ports:
      - '8081:80'
#      - '8082:80'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=${UPLOAD_LIMIT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /sessions
    depends_on:
      - php
      - mysql
    networks:
      - backend

volumes:
  MysqlVolume:

networks:
  backend: